// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/cards": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create card",
                "parameters": [
                    {
                        "description": "card without id and version",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/catalog_transport_http.CreateCardRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/catalog_transport_http.CardDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/cards/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Delete card",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "card id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Patch card",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "card id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "version is required",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/catalog_transport_http.PatchCardRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog_transport_http.CardDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/cards": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List cards",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "max 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "deck id",
                        "name": "deck_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog_transport_http.CardListDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/cards/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "Get card",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "card id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog_transport_http.CardDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/decks": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List decks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/catalog_transport_http.DeckDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/decks/{id}/cards": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "catalog"
                ],
                "summary": "List cards in a deck",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "deck id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "max 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/catalog_transport_http.CardListDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health_transport_http.StatusBody"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Readiness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health_transport_http.StatusBody"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/core_http_response.ErrorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "catalog_transport_http.CardDTO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deckId": {
                    "type": "integer"
                },
                "example": {
                    "type": "string"
                },
                "exampleHighlight": {
                    "type": "string"
                },
                "exampleRu": {
                    "type": "string"
                },
                "extra": {
                    "type": "string"
                },
                "extraLabel": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ipa": {
                    "type": "string"
                },
                "pos": {
                    "type": "string"
                },
                "posRu": {
                    "type": "string"
                },
                "rusTrans": {
                    "type": "string"
                },
                "stress": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "catalog_transport_http.CardListDTO": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/catalog_transport_http.CardDTO"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "catalog_transport_http.CreateCardRequest": {
            "type": "object",
            "properties": {
                "deckId": {
                    "type": "integer"
                },
                "example": {
                    "type": "string"
                },
                "exampleHighlight": {
                    "type": "string"
                },
                "exampleRu": {
                    "type": "string"
                },
                "extra": {
                    "type": "string"
                },
                "extraLabel": {
                    "type": "string"
                },
                "ipa": {
                    "type": "string"
                },
                "pos": {
                    "type": "string"
                },
                "posRu": {
                    "type": "string"
                },
                "rusTrans": {
                    "type": "string"
                },
                "stress": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "catalog_transport_http.DeckDTO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "catalog_transport_http.PatchCardRequest": {
            "type": "object",
            "properties": {
                "example": {
                    "type": "string"
                },
                "exampleHighlight": {
                    "type": "string"
                },
                "exampleRu": {
                    "type": "string"
                },
                "extra": {
                    "type": "string"
                },
                "extraLabel": {
                    "type": "string"
                },
                "ipa": {
                    "type": "string"
                },
                "pos": {
                    "type": "string"
                },
                "posRu": {
                    "type": "string"
                },
                "rusTrans": {
                    "type": "string"
                },
                "stress": {
                    "type": "string"
                },
                "style": {
                    "type": "string"
                },
                "translation": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                },
                "word": {
                    "type": "string"
                }
            }
        },
        "core_http_response.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "core_http_response.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/core_http_response.ErrorBody"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "health_transport_http.StatusBody": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Value is \"Bearer \u003cADMIN_TOKEN\u003e\". Do not put a real token here.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:5050",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Engmark API",
	Description:      "Card catalog. Admin writes require Authorization: Bearer <ADMIN_TOKEN>.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
